name: benchmarking
description: Provides tools to run benchmarks.
version: 0.1.0
repository: https://github.com/vaind/benchmarking.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
